version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    # Add: Healthcheck for Postgres to ensure services wait until DB is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data        # persists Redis data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 15              # increase retries to ensure readiness

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydb
      REDIS_URL: redis://redis:6379
      JWT_SECRET: secret
    ports:
      - "3001:3001"

    # Add: Depends on healthy Redis and fully ready Postgres to avoid connection issues
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://api:3001
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - api

  pusher:
    build:
      context: .
      dockerfile: docker/Dockerfile.pusher
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydb
      REDIS_URL: redis://redis:6379
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    # Add: Depends on healthy Redis and fully ready Postgres to avoid connection errors
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 65535
        hard: 65535


  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker 
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydb
      REDIS_URL: redis://redis:6379
      REGION_ID: f5a13f6c-8e91-42b8-9c0e-07b4567a98e0
      WORKER_ID: "1"
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    # Add: Depends on healthy Redis and fully ready Postgres to avoid connection errors
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 65535
        hard: 65535


volumes:
  postgres_data:
  redis_data: